modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://mcreator.net"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about. Ported to NeoForge 1.21.1"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="zombiekit"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
