modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "REQUIRED"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tacz"
type = "REQUIRED"
versionRange = "[1.1.8,)"
ordering = "AFTER"
side = "BOTH"
