# ---- Gradle ----
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
# 国内环境：如需代理，取消下面四行注释并改成你自己的端口
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=7890
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=7890

# ---- 平台 ----
minecraft_version=1.21.1
neoforge_version=21.1.255
pack_format=48

# ---- 模组身份 ----
mod_id=gearsandflesh_market
mod_name=Gears and Flesh Global Market
mod_name_cn=全球市场
mod_version=1.0.0
mod_group_id=com.gearsandflesh.market
mod_authors=齿轮与腐肉制作组
mod_license=All Rights Reserved
mod_description=Website-backed global player marketplace: shared listings, account balance and mailbox across singleplayer worlds and servers.
