package net.mcreator.survivalinstinct.init;

import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import java.util.List;
import java.util.Map;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ArmorMaterial;
import net.minecraft.world.item.ArmorItem.Type;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.Ingredient;
import net.neoforged.neoforge.registries.DeferredRegister;
public final class SurvivalInstinctModArmorMaterials {
    public static final DeferredRegister<ArmorMaterial> REGISTRY = DeferredRegister.create(Registries.ARMOR_MATERIAL, "survival_instinct");
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> ARTIC_GUILLIE = REGISTRY.register("artic_guillie", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 6, Type.CHESTPLATE, 8, Type.HELMET, 3), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("block.cherry_leaves.place"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "artic_guillie"))), 1.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> BLACK_JUGGERNAUT = REGISTRY.register("black_juggernaut", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 7, Type.CHESTPLATE, 9, Type.HELMET, 4), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_IV_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "black_juggernaut"))), 3.0F, 0.1F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> BLACK_RECLUIT_ARMOR = REGISTRY.register("black_recluit_armor", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 2), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_I_KEVLAR.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "black_recluit_armor"))), 0.5F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> BLACK_ROCKIE_ARMOR = REGISTRY.register("black_rockie_armor", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 2), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "black_rockie_armor"))), 2.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> CHICKEN_HEAD = REGISTRY.register("chicken_head", () -> new ArmorMaterial(Map.of(Type.BOOTS, 0, Type.LEGGINGS, 0, Type.CHESTPLATE, 0, Type.HELMET, 2), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(Items.FEATHER), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "chicken_head"))), 0.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> CLOTH_BALACLAVA = REGISTRY.register("cloth_balaclava", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 1), 12, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.CLOTH.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "cloth_balaclava"))), 0.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> DESERT_JUGGERNAUT = REGISTRY.register("desert_juggernaut", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 7, Type.CHESTPLATE, 9, Type.HELMET, 4), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_IV_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "desert_juggernaut"))), 3.0F, 0.1F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> DESERT_RECLUIT_ARMOR = REGISTRY.register("desert_recluit_armor", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 2), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_I_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "desert_recluit_armor"))), 0.5F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> DESERT_ROCKIE_ARMOR = REGISTRY.register("desert_rockie_armor", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 2), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "desert_rockie_armor"))), 2.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> EXO_HEAVY_BLACK = REGISTRY.register("exo_heavy_black", () -> new ArmorMaterial(Map.of(Type.BOOTS, 4, Type.LEGGINGS, 8, Type.CHESTPLATE, 10, Type.HELMET, 5), 16, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "exo_heavy_black"))), 4.0F, 0.1F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> EXO_HEAVY_DESERT = REGISTRY.register("exo_heavy_desert", () -> new ArmorMaterial(Map.of(Type.BOOTS, 4, Type.LEGGINGS, 8, Type.CHESTPLATE, 10, Type.HELMET, 5), 16, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "exo_heavy_desert"))), 4.0F, 0.1F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> EXO_HEAVY_GREEN = REGISTRY.register("exo_heavy_green", () -> new ArmorMaterial(Map.of(Type.BOOTS, 4, Type.LEGGINGS, 8, Type.CHESTPLATE, 10, Type.HELMET, 5), 16, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "exo_heavy_green"))), 4.0F, 0.1F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> EXO = REGISTRY.register("exo", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 6, Type.CHESTPLATE, 8, Type.HELMET, 3), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_netherite"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.STEELLIUM.get()), new ItemStack(SurvivalInstinctModItems.BATTERIES.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "exo"))), 2.0F, 0.1F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> FIRE_FIGHTER = REGISTRY.register("fire_fighter", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 6, Type.CHESTPLATE, 7, Type.HELMET, 3), 12, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "fire_fighter"))), 1.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> GAS_MASK = REGISTRY.register("gas_mask", () -> new ArmorMaterial(Map.of(Type.BOOTS, 0, Type.LEGGINGS, 0, Type.CHESTPLATE, 0, Type.HELMET, 3), 12, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "gas_mask"))), 0.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> GREEN_JUGGERNAUT = REGISTRY.register("green_juggernaut", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 7, Type.CHESTPLATE, 9, Type.HELMET, 4), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.THREAD.get()), new ItemStack(SurvivalInstinctModItems.TIER_IV_KEVLAR.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "green_juggernaut"))), 3.0F, 0.1F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> GREEN_RECLUIT_ARMOR = REGISTRY.register("green_recluit_armor", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 2), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_I_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "green_recluit_armor"))), 0.5F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> GREEN_ROCKIE_ARMOR = REGISTRY.register("green_rockie_armor", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 2), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "green_rockie_armor"))), 2.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> GUILLIE = REGISTRY.register("guillie", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 6, Type.CHESTPLATE, 8, Type.HELMET, 3), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("block.cherry_leaves.place"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "guillie"))), 1.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> HAZMAT = REGISTRY.register("hazmat", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 6, Type.CHESTPLATE, 7, Type.HELMET, 3), 12, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "hazmat"))), 2.5F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> MILITARY = REGISTRY.register("military", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 6, Type.CHESTPLATE, 7, Type.HELMET, 3), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "military"))), 1.5F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> MOTORCYCLE = REGISTRY.register("motorcycle", () -> new ArmorMaterial(Map.of(Type.BOOTS, 0, Type.LEGGINGS, 0, Type.CHESTPLATE, 0, Type.HELMET, 3), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.THREAD.get()), new ItemStack(SurvivalInstinctModItems.TIER_I_KEVLAR.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "motorcycle"))), 0.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> NIGHT_VISION_GOGGLES = REGISTRY.register("night_vision_goggles", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 1), 6, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.BATTERIES.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "night_vision_goggles"))), 0.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> POLICE = REGISTRY.register("police", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 4, Type.CHESTPLATE, 6, Type.HELMET, 1), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_I_KEVLAR.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "police"))), 0.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> SPRUCE_GUILLIE = REGISTRY.register("spruce_guillie", () -> new ArmorMaterial(Map.of(Type.BOOTS, 3, Type.LEGGINGS, 6, Type.CHESTPLATE, 8, Type.HELMET, 3), 9, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("block.cherry_leaves.place"))), () -> Ingredient.of(new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "spruce_guillie"))), 1.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> WOOL_BALACLAVA = REGISTRY.register("wool_balaclava", () -> new ArmorMaterial(Map.of(Type.BOOTS, 2, Type.LEGGINGS, 5, Type.CHESTPLATE, 6, Type.HELMET, 1), 12, BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))), () -> Ingredient.of(new ItemStack(Blocks.BLACK_WOOL), new ItemStack(SurvivalInstinctModItems.THREAD.get())), List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct", "wool_balaclava"))), 0.0F, 0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> BLACK_HUNTER = REGISTRY.register("black_hunter", () -> new ArmorMaterial(Map.of(Type.BOOTS,2,Type.LEGGINGS,5,Type.CHESTPLATE,6,Type.HELMET,3),9,BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))),()->Ingredient.of(
                  new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()),
                  new ItemStack(SurvivalInstinctModItems.BATTERIES.get()),
                  new ItemStack(SurvivalInstinctModItems.THREAD.get())
               ),List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct","black_hunter"))),2.0F,0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> DESERT_HUNTER = REGISTRY.register("desert_hunter", () -> new ArmorMaterial(Map.of(Type.BOOTS,2,Type.LEGGINGS,5,Type.CHESTPLATE,6,Type.HELMET,3),9,BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))),()->Ingredient.of(
                  new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()),
                  new ItemStack(SurvivalInstinctModItems.BATTERIES.get()),
                  new ItemStack(SurvivalInstinctModItems.THREAD.get())
               ),List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct","desert_hunter"))),2.0F,0.0F));
    public static final net.neoforged.neoforge.registries.DeferredHolder<ArmorMaterial, ArmorMaterial> GREEN_HUNTER = REGISTRY.register("green_hunter", () -> new ArmorMaterial(Map.of(Type.BOOTS,2,Type.LEGGINGS,5,Type.CHESTPLATE,6,Type.HELMET,3),9,BuiltInRegistries.SOUND_EVENT.getHolderOrThrow(net.minecraft.resources.ResourceKey.create(Registries.SOUND_EVENT, ResourceLocation.parse("item.armor.equip_leather"))),()->Ingredient.of(
                  new ItemStack(SurvivalInstinctModItems.TIER_II_KEVLAR.get()),
                  new ItemStack(SurvivalInstinctModItems.BATTERIES.get()),
                  new ItemStack(SurvivalInstinctModItems.THREAD.get())
               ),List.of(new ArmorMaterial.Layer(ResourceLocation.fromNamespaceAndPath("survival_instinct","green_hunter"))),2.0F,0.0F));
}
