pluginManagement {
    repositories {
        maven { name = 'NeoForged'; url = 'https://maven.neoforged.net/releases' }
        maven { name = 'AliyunPublic'; url = 'https://maven.aliyun.com/repository/public' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'tacz-unified-ammo'
