org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.255
loader_version_range=[1,)

mod_id=dyairdrop
mod_name=Realistic Airdrop
mod_license=MIT
mod_version=1.4.0
mod_group_id=net.gem19910816.dyairdrop
mod_authors=Ian, MCreator, gem19910816
mod_description=a realistic airdrop mode
geckolib_version=4.9.3
