org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.255
loader_version_range=[1,)

mod_id=zombiegamereborn
mod_name=ZombieGame:Reborn
mod_license=All Rights Reserved
mod_version=2.1.0
mod_group_id=com.aljun.zombiegamereborn
mod_authors=Aljun2007, DeepSeek
mod_description=The rebirth of ZombieGame [Mod] which enhances zombie AI to create apocalypse experience
